version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
    assignees:
      - nikcani
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
    assignees:
      - nikcani
    groups:
      nuget:
        patterns:
          - "*"
